title: KM-Data
logo: doc/assets/3.jpg
tagline: system developer
description: System developer
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#https://github.com/KM-Data/km-data.github.io/blob/772f2811097b4c6bb762436b70a382d627640c6c/doc/assets/KM400.jpg
